# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f0c292439bb2496f78a775253936067d70da0ebad8b8edafed7d9cb2dede1823870eb52895c015612d9b794831a6aa6d6447ab2118d1b1859f0c79cd6d2767

test:
  secret_key_base: 10351068e4ca57db76a223ed5b68bb81c08bd23e03e34160006457954c9e28aa44ef0a1fd9cb77ae5053becc3bf23ddebf7abcbc04cfbda43d6a64ccf7472f3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
